### PR TITLE
Require and use CoffeeLint directly instead of the CLI

### LINKED ISSUE #11: Does not work in Windows version of Atom
No errors, unsure if this is a coffeelint issue or an Atom issue
```coffeescript
command and arguments ["c:\Users\Dranor.ELEMENTAL\.atom\packages\linter-coffeelint\node_modules\coffeelint\bin\coffeelint", "--reporter", "jslint", "c:\Users\DRANOR~1.ELE\AppData\Local\Temp\114617-13008-ivbxrksource.coffee"] - linter.coffee - line 68
is node executable: true - linter.coffee - line 91
```

### LINKED ISSUE #17: jslint reporter outputs xml, but it doesn't get decoded
The jslint reporter outputs xml, but it doesn't get decoded. So you end up with entities in the output:

image

This can probably be most easily fixed by moving to the csv reporter.

### PR DESCRIPTION
**Pull request by AsaAyers**
Fixes #17 
Fixes #11 
Closes #18 

This PR should bring linter-coffeelint in line with the same behavior you get out of running the CLI by hand. It will pick up your project-specific configs and project-specific version of CoffeeLint.

There was an issue I had to fix in CoffeeLint https://github.com/clutchski/coffeelint/pull/383 to make it compatible. I pushed that out as v1.9.1 tonight.

### CODE REVIEW

File: lib/linter-coffeelint.coffee [hunk 1]
```diff
@@ -1,49 +1,63 @@
...
+
+  lintFile: (filePath, callback) ->
+    coffeeLintPath = @_resolveCoffeeLint(filepath)
+    coffeelint = require(coffeeLintPath)
+
+    # Versions before 1.9.1 don't work with atom because of an assumption that
+    # if window is defined, then it must be running in a browser. Atom breaks
+    # this assumption, so CoffeeLint < 1.9.1 will fail to find CoffeeScript.
+    # See https://github.com/clutchski/coffeelint/pull/383
+    [major, minor] = coffeelint.VERSION.split('.').map(toInt)
```
Comment (mattdeboard) [inline lib/linter-coffeelint.coffee]: I think you're missing a variable...?

```coffeescript
[major, minor, patch] = coffeelint.VERSION.split('.').map(toInt)
```

Comment (AsaAyers) [inline lib/linter-coffeelint.coffee]: yup, thanks.

**Comment by AsaAyers** [comment]
Any word on getting this merged?
